# This role binding allows users to bind manage secrets
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: secrets-admin-binding
subjects:
  - kind: User
    name: "user-with-secret-access"
roleRef:
  kind: ClusterRole
  name: secrets-admin-all
  apiVersion: rbac.authorization.k8s.io/v1alpha1
