---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: kubelet-runtime
rules:
  - apiGroups:
      - ""
    nonResourceURLs: []
    resources:
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
      - secrets
      - services
      - healthz
      - namespaces
    verbs: ["get", "watch", "list"]
  - apiGroups: []
    nonResourceURLs: ["*"]
    resources: []
    verbs: ["get"]
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    nonResourceURLs: []
    resources:
      - events
      - nodes
      - nodes/status
      - pods
      - pods/status
    verbs: ["*"]
